// Generated by scripts/rkgenerateproduct.py; do not edit.

export type CommandFieldValue = null | boolean | number | string | CommandFieldValue[] | {readonly [key: string]: CommandFieldValue};

export type ScopeKind = "GLOBAL" | "RUN" | "DEPLOYMENT";

export type ReceiptState = "PENDING" | "DECIDED" | "OUTCOME_UNKNOWN";

export type CommandType = "CREATE_RESEARCH" | "CONFIRM_CONTRACT" | "AMEND_CONTRACT" | "APPLY_ROUTE_PLAN" | "START_RESEARCH" | "PAUSE_RESEARCH" | "RESUME_RESEARCH" | "CANCEL_RESEARCH" | "SUBMIT_GUIDANCE" | "WITHDRAW_GUIDANCE" | "SUBMIT_CLAIM" | "IMPORT_VERIFICATION" | "CONFIRM_REVOKE" | "REGISTER_BRIDGE_SPEC" | "SUBMIT_CLOSURE_WITNESS" | "CREATE_REVIEW_TASK" | "CLAIM_REVIEW_TASK" | "SUBMIT_REVIEW" | "GENERATE_CANDIDATE_TEX" | "SUBMIT_PAPER_REVIEW" | "FINALIZE_RESEARCH" | "COMPILE_FINAL_PDF" | "CONFIRM_MATERIAL_EXTRACTION" | "RUN_LITERATURE_QUERY" | "REPLAY_SOURCE_SNAPSHOT" | "REVIEW_THEOREM_APPLICABILITY" | "FREEZE_PROBLEM_POOL" | "BATCH_CREATE_RESEARCH" | "REGISTER_BRIDGE_OPPORTUNITY" | "ASSIGN_ABLATION" | "IMPORT_RESEARCH_LINEAGE" | "CREATE_COMPUTE_TASK" | "RUN_TOOL" | "CANCEL_JOB" | "RETRY_UNKNOWN_OUTCOME" | "DEPLOYMENT_OPERATION";

export type QueryType = "LIST_RESEARCH" | "RESEARCH_OVERVIEW" | "CONTRACT" | "CONTRACT_IMPACT" | "MATERIAL" | "MATERIAL_EXTRACTION" | "CITATION_ANCHOR" | "EXTRACTION_DIFF" | "LITERATURE_QUERY" | "SOURCE_SNAPSHOT" | "LITERATURE_SOURCE" | "LITERATURE_GRAPH" | "THEOREM_APPLICABILITY" | "PRIOR_ART_COMPARISON" | "NOVELTY_REVIEW" | "PROBLEM_POOL" | "PROBLEM_CANDIDATE" | "SOURCE_VERSION_HISTORY" | "BATCH_RESEARCH_JOB" | "ROUTE_PLAN" | "BRIDGE_OPPORTUNITIES" | "ABLATION_PLAN" | "ABLATION_RESULTS" | "WORKFLOW" | "WORK_ITEM" | "WORKER_RUN" | "CHECKPOINT" | "CLAIM" | "CLAIM_HISTORY" | "AVAILABLE_ACTIONS" | "GRAPH_SLICE" | "GRAPH_SEARCH" | "DEPENDENCY_CLOSURE" | "REVERSE_CLOSURE" | "REVOKE_PREVIEW" | "COMPUTE_TASK" | "TOOL_CATALOG" | "TOOL_RUN" | "GUIDANCE_INBOX" | "HINT" | "REVIEW_INBOX" | "REVIEW_TASK" | "DOSSIER" | "PUBLICATION_STATUS" | "ARTIFACT_INDEX" | "RESEARCH_CASE_LINEAGE" | "CLEAN_ROOM_INPUT_MANIFEST" | "CERTIFICATE_IMPORT_REPORT" | "ACTION_ITEMS" | "PRODUCT_RECEIPT" | "JOB" | "DEPLOYMENT_STATUS" | "DEPLOYMENT_JOB" | "BACKUP_STATUS" | "ADMIN_HEALTH" | "USAGE";

export type ArtifactOperationType = "BEGIN_UPLOAD" | "APPEND_CHUNK" | "COMMIT_UPLOAD" | "READ_RANGE" | "TAIL_LOG" | "DESCRIBE";

export type ReviewType = "ATOMIC" | "COMPOSITION" | "PAPER";

export type WorkflowObjectType = "MATERIAL_EXTRACTION" | "SOURCE_SNAPSHOT" | "LITERATURE_GRAPH" | "THEOREM_APPLICABILITY" | "PROBLEM_POOL" | "PROBLEM_CANDIDATE" | "BRIDGE_OPPORTUNITY" | "ABLATION_PLAN" | "RESEARCH_CASE_LINEAGE";

export type PublicActivitySource = "KERNEL" | "ORCHESTRATOR" | "WORKER" | "TOOL" | "REVIEW" | "DEPLOYMENT";

export type ProductErrorCode = "REVISION_CONFLICT" | "CAPABILITY_DENIED" | "CONTRACT_VERSION_MISMATCH" | "IDEMPOTENCY_KEY_REUSED" | "STABLE_LABEL_CONFLICT" | "STALE_QUERY" | "CURSOR_EXPIRED" | "PROJECTION_LAG" | "REVIEW_BINDING_MISMATCH" | "CHECKPOINT_STALE" | "REVOCATION_PREVIEW_STALE" | "PAPER_BINDING_STALE" | "RUN_CLOSED" | "COMPOSITION_OPEN" | "TERMINAL_ROOT_REQUIRED" | "PAPER_REVIEW_REQUIRED" | "TOOL_RESULT_NOT_AUTHORITY" | "EXTERNAL_BLOCKED" | "OUTCOME_UNKNOWN" | "UNKNOWN_VARIANT";

export interface CommandPayloadMap {
  CREATE_RESEARCH: {contract_draft: CommandFieldValue; initial_budget: CommandFieldValue; labels: CommandFieldValue; owner: CommandFieldValue; question: CommandFieldValue; material_artifacts?: CommandFieldValue; title?: CommandFieldValue};
  CONFIRM_CONTRACT: {confirmation_note: CommandFieldValue; contract_digest: CommandFieldValue; material_anchor_ids: CommandFieldValue};
  AMEND_CONTRACT: {amendment_artifact: CommandFieldValue; base_contract_version: CommandFieldValue; impact_acknowledgement: CommandFieldValue};
  APPLY_ROUTE_PLAN: {action: CommandFieldValue; route_plan_id: CommandFieldValue; budget?: CommandFieldValue; plan_digest?: CommandFieldValue; priority?: CommandFieldValue; reason?: CommandFieldValue};
  START_RESEARCH: {checkpoint_id: CommandFieldValue; route_plan_id: CommandFieldValue};
  PAUSE_RESEARCH: {checkpoint_required: CommandFieldValue; reason: CommandFieldValue};
  RESUME_RESEARCH: {checkpoint_id: CommandFieldValue; resume_invalidated_items: CommandFieldValue};
  CANCEL_RESEARCH: {cancel_pending_external_attempts: CommandFieldValue; reason: CommandFieldValue};
  SUBMIT_GUIDANCE: {affected_route_ids: CommandFieldValue; goal: CommandFieldValue; guidance_text: CommandFieldValue; target_checkpoint_id: CommandFieldValue};
  WITHDRAW_GUIDANCE: {guidance_id: CommandFieldValue; reason: CommandFieldValue};
  SUBMIT_CLAIM: {attempt_id: CommandFieldValue; claim_kind: CommandFieldValue; predecessor_fact_ids: CommandFieldValue; proof_or_evidence_artifacts: CommandFieldValue; source_binding_artifact: CommandFieldValue; statement: CommandFieldValue; work_item_id: CommandFieldValue; worker_run_id: CommandFieldValue; public_summary?: CommandFieldValue; route_id?: CommandFieldValue; supersedes_claim_id?: CommandFieldValue};
  IMPORT_VERIFICATION: {review_task_id: CommandFieldValue; signed_review_artifact: CommandFieldValue; target_digest: CommandFieldValue; verifier_receipt_ids: CommandFieldValue};
  CONFIRM_REVOKE: {affected_fact_ids: CommandFieldValue; contract_version: CommandFieldValue; fact_id: CommandFieldValue; preserved_sibling_ids: CommandFieldValue; preview_revision: CommandFieldValue; reason_artifact: CommandFieldValue; reopened_obligation_ids: CommandFieldValue; target_fact_digest: CommandFieldValue};
  REGISTER_BRIDGE_SPEC: {assumption_loss_artifact: CommandFieldValue; bridge_opportunity_id: CommandFieldValue; composition_obligation_ids: CommandFieldValue; direction: CommandFieldValue; mapping_artifact: CommandFieldValue; source_domain: CommandFieldValue; target_domain: CommandFieldValue; target_review_artifact: CommandFieldValue; translation_artifact: CommandFieldValue};
  SUBMIT_CLOSURE_WITNESS: {bridge_spec_ids: CommandFieldValue; composition_obligation_ids: CommandFieldValue; edge_justification_artifacts: CommandFieldValue; graph_revision: CommandFieldValue; selected_subgraph_digest: CommandFieldValue; terminal_root_id: CommandFieldValue; verification_review_ids: CommandFieldValue};
  CREATE_REVIEW_TASK: {assignee_subject_id: CommandFieldValue; author_subject_ids: CommandFieldValue; expires_at: CommandFieldValue; independence_constraints: CommandFieldValue; review_type: CommandFieldValue; target_digest: CommandFieldValue; target_entity_ids: CommandFieldValue};
  CLAIM_REVIEW_TASK: {review_task_id: CommandFieldValue; task_binding_digest: CommandFieldValue};
  SUBMIT_REVIEW: {review_schema_version: CommandFieldValue; review_task_id: CommandFieldValue; signed_review_artifact: CommandFieldValue; task_binding_digest: CommandFieldValue};
  GENERATE_CANDIDATE_TEX: {dependency_closure_digest: CommandFieldValue; finalized_revision: CommandFieldValue; template_artifact: CommandFieldValue; terminal_root_id: CommandFieldValue};
  SUBMIT_PAPER_REVIEW: {candidate_tex_artifact: CommandFieldValue; paper_review_schema_version: CommandFieldValue; review_task_id: CommandFieldValue; signed_paper_review_artifact: CommandFieldValue};
  FINALIZE_RESEARCH: {closure_witness_id: CommandFieldValue; final_outcome: CommandFieldValue; terminal_root_id: CommandFieldValue};
  COMPILE_FINAL_PDF: {candidate_tex_artifact: CommandFieldValue; compiler_profile_id: CommandFieldValue; compiler_profile_version: CommandFieldValue; paper_review_id: CommandFieldValue};
  CONFIRM_MATERIAL_EXTRACTION: {corrections_artifact: CommandFieldValue; extraction_digest: CommandFieldValue; material_extraction_id: CommandFieldValue; reviewed_page_numbers: CommandFieldValue; source_artifact: CommandFieldValue};
  RUN_LITERATURE_QUERY: {capture_raw_response: CommandFieldValue; connector_profile_ids: CommandFieldValue; coverage_boundary: CommandFieldValue; query_text: CommandFieldValue; research_question: CommandFieldValue; target_entity_ids: CommandFieldValue};
  REPLAY_SOURCE_SNAPSHOT: {expected_response_sha256: CommandFieldValue; reconfirm_external_index: CommandFieldValue; source_snapshot_id: CommandFieldValue};
  REVIEW_THEOREM_APPLICABILITY: {assumption_mapping_artifact: CommandFieldValue; signed_review_artifact: CommandFieldValue; target_claim_id: CommandFieldValue; theorem_source_binding: CommandFieldValue; verdict: CommandFieldValue};
  FREEZE_PROBLEM_POOL: {candidate_denominator: CommandFieldValue; exclusion_rules: CommandFieldValue; frozen_at: CommandFieldValue; inclusion_rules: CommandFieldValue; pool_name: CommandFieldValue; semantic_audit_artifact: CommandFieldValue; source_snapshot_ids: CommandFieldValue; subject_classes: CommandFieldValue; version_rule: CommandFieldValue};
  BATCH_CREATE_RESEARCH: {contract_template_artifact: CommandFieldValue; labels: CommandFieldValue; per_run_budget: CommandFieldValue; problem_candidate_ids: CommandFieldValue; problem_pool_id: CommandFieldValue};
  REGISTER_BRIDGE_OPPORTUNITY: {candidate_target_domain: CommandFieldValue; domain_distance_basis: CommandFieldValue; expected_certificate_compression: CommandFieldValue; fastest_death_test: CommandFieldValue; mapping_and_assumption_losses: CommandFieldValue; native_tool_advantage: CommandFieldValue; normalized_source_problem: CommandFieldValue; round_trip_and_source_review_cost: CommandFieldValue; selection_rationale: CommandFieldValue; source_method_maturity: CommandFieldValue; source_snapshot_ids: CommandFieldValue; target_domain_absence_evidence: CommandFieldValue};
  ASSIGN_ABLATION: {ablation_plan_id: CommandFieldValue; budget: CommandFieldValue; candidate_count: CommandFieldValue; final_verifier_profile: CommandFieldValue; group: CommandFieldValue; model_profile: CommandFieldValue; problem_candidate_ids: CommandFieldValue; tool_profile: CommandFieldValue};
  IMPORT_RESEARCH_LINEAGE: {mode: CommandFieldValue; source_project_id: CommandFieldValue; source_versions: CommandFieldValue; candidate_artifacts?: CommandFieldValue; certificate_import_report?: CommandFieldValue; clean_room_input_manifest?: CommandFieldValue; historical_conclusions_injected?: CommandFieldValue; imported_artifacts?: CommandFieldValue; promote_as_verified?: CommandFieldValue; verifier_receipt_ids?: CommandFieldValue};
  CREATE_COMPUTE_TASK: {environment_profile_id: CommandFieldValue; environment_profile_version: CommandFieldValue; expected_output_names: CommandFieldValue; input_artifacts: CommandFieldValue; limits_artifact: CommandFieldValue; parameters_artifact: CommandFieldValue; script_artifact: CommandFieldValue};
  RUN_TOOL: {arguments_artifact: CommandFieldValue; authority_ceiling: CommandFieldValue; function_name: CommandFieldValue; function_schema_digest: CommandFieldValue; input_artifact_ids: CommandFieldValue; tool_id: CommandFieldValue; tool_version: CommandFieldValue};
  CANCEL_JOB: {job_id: CommandFieldValue; reason: CommandFieldValue};
  RETRY_UNKNOWN_OUTCOME: {evidence_artifact_ids: CommandFieldValue; outcome_unknown_receipt_id: CommandFieldValue; resolution_strategy: CommandFieldValue; unknown_external_call_ref: CommandFieldValue};
  DEPLOYMENT_OPERATION: {action: CommandFieldValue; backup_artifact?: CommandFieldValue; backup_id?: CommandFieldValue; backup_target?: CommandFieldValue; capability_profile_id?: CommandFieldValue; component_manifest?: CommandFieldValue; configuration_artifact?: CommandFieldValue; daemon_id?: CommandFieldValue; data_root?: CommandFieldValue; drain_timeout_seconds?: CommandFieldValue; expected_config_digest?: CommandFieldValue; include_cas?: CommandFieldValue; include_configuration?: CommandFieldValue; inventory_profile_id?: CommandFieldValue; new_data_root?: CommandFieldValue; redact_credentials?: CommandFieldValue; release_manifest?: CommandFieldValue};
}

export type ProductCommand = {[K in CommandType]: {type: K; payload: CommandPayloadMap[K]}}[CommandType];

export interface QueryPayloadMap {
  ABLATION_PLAN: {ablation_plan_id: CommandFieldValue};
  ABLATION_RESULTS: {ablation_plan_id: CommandFieldValue; page: CommandFieldValue};
  ACTION_ITEMS: {page: CommandFieldValue};
  ADMIN_HEALTH: {};
  ARTIFACT_INDEX: {page: CommandFieldValue};
  AVAILABLE_ACTIONS: {};
  BACKUP_STATUS: {backup_id: CommandFieldValue};
  BATCH_RESEARCH_JOB: {batch_job_id: CommandFieldValue};
  BRIDGE_OPPORTUNITIES: {page: CommandFieldValue};
  CERTIFICATE_IMPORT_REPORT: {report_id: CommandFieldValue};
  CHECKPOINT: {checkpoint_id: CommandFieldValue};
  CITATION_ANCHOR: {anchor_id: CommandFieldValue};
  CLAIM: {claim_id: CommandFieldValue};
  CLAIM_HISTORY: {claim_id: CommandFieldValue; page: CommandFieldValue};
  CLEAN_ROOM_INPUT_MANIFEST: {manifest_id: CommandFieldValue};
  COMPUTE_TASK: {compute_task_id: CommandFieldValue};
  CONTRACT: {contract_id: CommandFieldValue};
  CONTRACT_IMPACT: {impact_preview_id: CommandFieldValue};
  DEPENDENCY_CLOSURE: {at_revision: CommandFieldValue; claim_id: CommandFieldValue; node_limit: CommandFieldValue; continuation_cursor?: CommandFieldValue};
  DEPLOYMENT_JOB: {deployment_job_id: CommandFieldValue};
  DEPLOYMENT_STATUS: {};
  DOSSIER: {dossier_id: CommandFieldValue};
  EXTRACTION_DIFF: {after_extraction_id: CommandFieldValue; before_extraction_id: CommandFieldValue};
  GRAPH_SEARCH: {at_revision: CommandFieldValue; mode: CommandFieldValue; page: CommandFieldValue; text: CommandFieldValue};
  GRAPH_SLICE: {at_revision: CommandFieldValue; depth: CommandFieldValue; direction: CommandFieldValue; filters: CommandFieldValue; mode: CommandFieldValue; node_limit: CommandFieldValue; seed_ids: CommandFieldValue; continuation_cursor?: CommandFieldValue};
  GUIDANCE_INBOX: {page: CommandFieldValue};
  HINT: {hint_id: CommandFieldValue};
  JOB: {job_id: CommandFieldValue};
  LIST_RESEARCH: {page: CommandFieldValue; labels?: CommandFieldValue; outcomes?: CommandFieldValue; owners?: CommandFieldValue; sort?: CommandFieldValue; text?: CommandFieldValue};
  LITERATURE_GRAPH: {literature_graph_id: CommandFieldValue; page: CommandFieldValue};
  LITERATURE_QUERY: {literature_query_id: CommandFieldValue};
  LITERATURE_SOURCE: {literature_source_id: CommandFieldValue};
  MATERIAL: {material_id: CommandFieldValue};
  MATERIAL_EXTRACTION: {extraction_id: CommandFieldValue};
  NOVELTY_REVIEW: {novelty_review_id: CommandFieldValue};
  PRIOR_ART_COMPARISON: {comparison_id: CommandFieldValue};
  PROBLEM_CANDIDATE: {problem_candidate_id: CommandFieldValue};
  PROBLEM_POOL: {problem_pool_id: CommandFieldValue};
  PRODUCT_RECEIPT: {receipt_id: CommandFieldValue};
  PUBLICATION_STATUS: {};
  RESEARCH_CASE_LINEAGE: {lineage_id: CommandFieldValue};
  RESEARCH_OVERVIEW: {};
  REVERSE_CLOSURE: {at_revision: CommandFieldValue; claim_id: CommandFieldValue; node_limit: CommandFieldValue; continuation_cursor?: CommandFieldValue};
  REVIEW_INBOX: {page: CommandFieldValue};
  REVIEW_TASK: {review_task_id: CommandFieldValue};
  REVOKE_PREVIEW: {at_revision: CommandFieldValue; claim_id: CommandFieldValue; target_digest: CommandFieldValue};
  ROUTE_PLAN: {route_plan_id: CommandFieldValue};
  SOURCE_SNAPSHOT: {source_snapshot_id: CommandFieldValue};
  SOURCE_VERSION_HISTORY: {page: CommandFieldValue; source_stable_id: CommandFieldValue};
  THEOREM_APPLICABILITY: {applicability_review_id: CommandFieldValue};
  TOOL_CATALOG: {page: CommandFieldValue};
  TOOL_RUN: {tool_run_id: CommandFieldValue};
  USAGE: {from: CommandFieldValue; granularity: CommandFieldValue; page: CommandFieldValue; to: CommandFieldValue};
  WORKER_RUN: {page?: CommandFieldValue; worker_run_id?: CommandFieldValue};
  WORKFLOW: {};
  WORK_ITEM: {page?: CommandFieldValue; work_item_id?: CommandFieldValue};
}

export const QUERY_CONTRACTS = {
  "ABLATION_PLAN": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "ablation_plan_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "ABLATION_RESULTS": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "ablation_plan_id",
      "page"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "ACTION_ITEMS": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "page"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "ADMIN_HEALTH": {
    "optional_payload_fields": [],
    "required_payload_fields": [],
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "ARTIFACT_INDEX": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "page"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "AVAILABLE_ACTIONS": {
    "optional_payload_fields": [],
    "required_payload_fields": [],
    "scope_kinds": [
      "RUN"
    ]
  },
  "BACKUP_STATUS": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "backup_id"
    ],
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "BATCH_RESEARCH_JOB": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "batch_job_id"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "BRIDGE_OPPORTUNITIES": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "page"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CERTIFICATE_IMPORT_REPORT": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "report_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CHECKPOINT": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "checkpoint_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CITATION_ANCHOR": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "anchor_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CLAIM": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "claim_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CLAIM_HISTORY": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "claim_id",
      "page"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CLEAN_ROOM_INPUT_MANIFEST": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "manifest_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "COMPUTE_TASK": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "compute_task_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CONTRACT": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "contract_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CONTRACT_IMPACT": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "impact_preview_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "DEPENDENCY_CLOSURE": {
    "optional_payload_fields": [
      "continuation_cursor"
    ],
    "required_payload_fields": [
      "at_revision",
      "claim_id",
      "node_limit"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "DEPLOYMENT_JOB": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "deployment_job_id"
    ],
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "DEPLOYMENT_STATUS": {
    "optional_payload_fields": [],
    "required_payload_fields": [],
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "DOSSIER": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "dossier_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "EXTRACTION_DIFF": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "after_extraction_id",
      "before_extraction_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "GRAPH_SEARCH": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "at_revision",
      "mode",
      "page",
      "text"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "GRAPH_SLICE": {
    "optional_payload_fields": [
      "continuation_cursor"
    ],
    "required_payload_fields": [
      "at_revision",
      "depth",
      "direction",
      "filters",
      "mode",
      "node_limit",
      "seed_ids"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "GUIDANCE_INBOX": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "page"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "HINT": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "hint_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "JOB": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "job_id"
    ],
    "scope_kinds": [
      "DEPLOYMENT",
      "GLOBAL",
      "RUN"
    ]
  },
  "LIST_RESEARCH": {
    "optional_payload_fields": [
      "labels",
      "outcomes",
      "owners",
      "sort",
      "text"
    ],
    "required_payload_fields": [
      "page"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "LITERATURE_GRAPH": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "literature_graph_id",
      "page"
    ],
    "scope_kinds": [
      "DEPLOYMENT",
      "RUN"
    ]
  },
  "LITERATURE_QUERY": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "literature_query_id"
    ],
    "scope_kinds": [
      "DEPLOYMENT",
      "RUN"
    ]
  },
  "LITERATURE_SOURCE": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "literature_source_id"
    ],
    "scope_kinds": [
      "DEPLOYMENT",
      "RUN"
    ]
  },
  "MATERIAL": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "material_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "MATERIAL_EXTRACTION": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "extraction_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "NOVELTY_REVIEW": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "novelty_review_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "PRIOR_ART_COMPARISON": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "comparison_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "PROBLEM_CANDIDATE": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "problem_candidate_id"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "PROBLEM_POOL": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "problem_pool_id"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "PRODUCT_RECEIPT": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "receipt_id"
    ],
    "scope_kinds": [
      "DEPLOYMENT",
      "GLOBAL",
      "RUN"
    ]
  },
  "PUBLICATION_STATUS": {
    "optional_payload_fields": [],
    "required_payload_fields": [],
    "scope_kinds": [
      "RUN"
    ]
  },
  "RESEARCH_CASE_LINEAGE": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "lineage_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "RESEARCH_OVERVIEW": {
    "optional_payload_fields": [],
    "required_payload_fields": [],
    "scope_kinds": [
      "RUN"
    ]
  },
  "REVERSE_CLOSURE": {
    "optional_payload_fields": [
      "continuation_cursor"
    ],
    "required_payload_fields": [
      "at_revision",
      "claim_id",
      "node_limit"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "REVIEW_INBOX": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "page"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "REVIEW_TASK": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "review_task_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "REVOKE_PREVIEW": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "at_revision",
      "claim_id",
      "target_digest"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "ROUTE_PLAN": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "route_plan_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "SOURCE_SNAPSHOT": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "source_snapshot_id"
    ],
    "scope_kinds": [
      "DEPLOYMENT",
      "RUN"
    ]
  },
  "SOURCE_VERSION_HISTORY": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "page",
      "source_stable_id"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "THEOREM_APPLICABILITY": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "applicability_review_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "TOOL_CATALOG": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "page"
    ],
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "TOOL_RUN": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "tool_run_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "USAGE": {
    "optional_payload_fields": [],
    "required_payload_fields": [
      "from",
      "granularity",
      "page",
      "to"
    ],
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "WORKER_RUN": {
    "optional_payload_fields": [
      "page",
      "worker_run_id"
    ],
    "required_payload_fields": [],
    "scope_kinds": [
      "RUN"
    ]
  },
  "WORKFLOW": {
    "optional_payload_fields": [],
    "required_payload_fields": [],
    "scope_kinds": [
      "RUN"
    ]
  },
  "WORK_ITEM": {
    "optional_payload_fields": [
      "page",
      "work_item_id"
    ],
    "required_payload_fields": [],
    "scope_kinds": [
      "RUN"
    ]
  }
} as const;

export const QUERY_RESULT_CONTRACTS = {
  "ABLATION_PLAN": {
    "domain_fields": [
      "ablation_plan_id",
      "opportunity_id",
      "baseline_digest",
      "variant_digests",
      "plan_state"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "ablation_plan_id",
      "opportunity_id",
      "baseline_digest",
      "variant_digests",
      "plan_state"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "ABLATION_RESULTS": {
    "domain_fields": [
      "ablation_result_id",
      "ablation_plan_id",
      "baseline_metric_microunits",
      "variant_metric_microunits",
      "result_artifact_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "ablation_result_id",
      "ablation_plan_id",
      "baseline_metric_microunits",
      "variant_metric_microunits",
      "result_artifact_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "ACTION_ITEMS": {
    "domain_fields": [],
    "projection_fields": [
      "stable_entity_id",
      "run_id",
      "command_type",
      "target_ids",
      "required_inputs",
      "blocked_by",
      "research_revision",
      "contract_version"
    ],
    "required_domain_fields": [],
    "required_projection_fields": [
      "stable_entity_id",
      "run_id",
      "command_type",
      "target_ids",
      "required_inputs",
      "blocked_by",
      "research_revision",
      "contract_version"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "ADMIN_HEALTH": {
    "domain_fields": [
      "health_report_id",
      "deployment_id",
      "overall_state",
      "probe_run_id",
      "fault_codes"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "health_report_id",
      "deployment_id",
      "overall_state",
      "probe_run_id",
      "fault_codes"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "ARTIFACT_INDEX": {
    "domain_fields": [
      "artifact_id",
      "artifact_digest",
      "byte_count",
      "media_type",
      "ingest_state"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "artifact_id",
      "artifact_digest",
      "byte_count",
      "media_type",
      "ingest_state"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "AVAILABLE_ACTIONS": {
    "domain_fields": [
      "action_set_id",
      "allowed_command_types",
      "expected_revision",
      "expected_contract_version",
      "guard_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "action_set_id",
      "allowed_command_types",
      "expected_revision",
      "expected_contract_version",
      "guard_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "BACKUP_STATUS": {
    "domain_fields": [
      "backup_id",
      "deployment_id",
      "backup_state",
      "backup_artifact_id",
      "backup_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "backup_id",
      "deployment_id",
      "backup_state",
      "backup_artifact_id",
      "backup_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "BATCH_RESEARCH_JOB": {
    "domain_fields": [
      "batch_job_id",
      "job_state",
      "total_count",
      "succeeded_count",
      "failed_count"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "batch_job_id",
      "job_state",
      "total_count",
      "succeeded_count",
      "failed_count"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "BRIDGE_OPPORTUNITIES": {
    "domain_fields": [
      "opportunity_id",
      "source_domain",
      "target_domain",
      "distance_microunits",
      "death_test_state"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "opportunity_id",
      "source_domain",
      "target_domain",
      "distance_microunits",
      "death_test_state"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "CERTIFICATE_IMPORT_REPORT": {
    "domain_fields": [
      "report_id",
      "lineage_id",
      "certificate_artifact_id",
      "verifier_profile_id",
      "verification_outcome"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "report_id",
      "lineage_id",
      "certificate_artifact_id",
      "verifier_profile_id",
      "verification_outcome"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "CHECKPOINT": {
    "domain_fields": [
      "checkpoint_id",
      "route_id",
      "checkpoint_revision",
      "checkpoint_state",
      "checkpoint_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "checkpoint_id",
      "route_id",
      "checkpoint_revision",
      "checkpoint_state",
      "checkpoint_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "CITATION_ANCHOR": {
    "domain_fields": [
      "anchor_id",
      "material_id",
      "source_artifact_id",
      "locator",
      "extraction_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "anchor_id",
      "material_id",
      "source_artifact_id",
      "locator",
      "extraction_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "CLAIM": {
    "domain_fields": [
      "claim_id",
      "stable_label",
      "lifecycle",
      "machine_state",
      "semantic_state",
      "statement_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "claim_id",
      "stable_label",
      "lifecycle",
      "machine_state",
      "semantic_state",
      "statement_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "CLAIM_HISTORY": {
    "domain_fields": [
      "claim_id",
      "claim_revision",
      "lifecycle",
      "statement_digest",
      "supersedes_claim_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "claim_id",
      "claim_revision",
      "lifecycle",
      "statement_digest",
      "supersedes_claim_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "CLEAN_ROOM_INPUT_MANIFEST": {
    "domain_fields": [
      "manifest_id",
      "lineage_id",
      "input_artifact_ids",
      "manifest_digest",
      "lineage_mode"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "manifest_id",
      "lineage_id",
      "input_artifact_ids",
      "manifest_digest",
      "lineage_mode"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "COMPUTE_TASK": {
    "domain_fields": [
      "compute_task_id",
      "task_type",
      "task_state",
      "input_digest",
      "output_artifact_ids"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "compute_task_id",
      "task_type",
      "task_state",
      "input_digest",
      "output_artifact_ids"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "CONTRACT": {
    "domain_fields": [
      "contract_id",
      "contract_version",
      "contract_state",
      "content_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "contract_id",
      "contract_version",
      "contract_state",
      "content_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "CONTRACT_IMPACT": {
    "domain_fields": [
      "impact_preview_id",
      "base_contract_version",
      "affected_object_ids",
      "impact_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "impact_preview_id",
      "base_contract_version",
      "affected_object_ids",
      "impact_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "DEPENDENCY_CLOSURE": {
    "domain_fields": [
      "claim_id",
      "graph_mode",
      "dependable",
      "distance",
      "boundary_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "claim_id",
      "graph_mode",
      "dependable",
      "distance",
      "boundary_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "DEPLOYMENT_JOB": {
    "domain_fields": [
      "deployment_job_id",
      "deployment_id",
      "job_type",
      "job_state",
      "execution_receipt_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "deployment_job_id",
      "deployment_id",
      "job_type",
      "job_state",
      "execution_receipt_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "DEPLOYMENT_STATUS": {
    "domain_fields": [
      "deployment_id",
      "deployment_state",
      "probe_run_id",
      "capability_keys",
      "fault_codes"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "deployment_id",
      "deployment_state",
      "probe_run_id",
      "capability_keys",
      "fault_codes"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "DOSSIER": {
    "domain_fields": [
      "dossier_id",
      "dossier_state",
      "observed_revision",
      "dossier_artifact_id",
      "dossier_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "dossier_id",
      "dossier_state",
      "observed_revision",
      "dossier_artifact_id",
      "dossier_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "EXTRACTION_DIFF": {
    "domain_fields": [
      "diff_id",
      "before_extraction_id",
      "after_extraction_id",
      "changed_regions",
      "diff_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "diff_id",
      "before_extraction_id",
      "after_extraction_id",
      "changed_regions",
      "diff_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "GRAPH_SEARCH": {
    "domain_fields": [
      "claim_id",
      "graph_mode",
      "dependable",
      "distance",
      "statement_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "claim_id",
      "graph_mode",
      "dependable",
      "distance",
      "statement_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "GRAPH_SLICE": {
    "domain_fields": [],
    "projection_fields": [],
    "required_domain_fields": [],
    "required_projection_fields": [],
    "result_kind": "graph",
    "scope_kinds": [
      "RUN"
    ]
  },
  "GUIDANCE_INBOX": {
    "domain_fields": [
      "hint_id",
      "hint_kind",
      "hint_state",
      "checkpoint_id",
      "target_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "hint_id",
      "hint_kind",
      "hint_state",
      "checkpoint_id",
      "target_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "HINT": {
    "domain_fields": [
      "hint_id",
      "hint_kind",
      "hint_state",
      "checkpoint_id",
      "target_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "hint_id",
      "hint_kind",
      "hint_state",
      "checkpoint_id",
      "target_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "JOB": {
    "domain_fields": [
      "job_id",
      "job_type",
      "job_state",
      "retry_safety",
      "result_receipt_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "job_id",
      "job_type",
      "job_state",
      "retry_safety",
      "result_receipt_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT",
      "GLOBAL",
      "RUN"
    ]
  },
  "LIST_RESEARCH": {
    "domain_fields": [],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "run_id",
      "title",
      "question_summary",
      "owner",
      "labels",
      "outcome_state",
      "execution_state",
      "authority_state",
      "publication_state",
      "phase",
      "blockers",
      "next_actions",
      "budget",
      "recent_activity_at",
      "recent_activity_summary",
      "research_revision",
      "contract_version",
      "last_cursor"
    ],
    "required_domain_fields": [],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "run_id",
      "title",
      "question_summary",
      "owner",
      "labels",
      "outcome_state",
      "execution_state",
      "authority_state",
      "publication_state",
      "phase",
      "blockers",
      "next_actions",
      "budget",
      "recent_activity_at",
      "recent_activity_summary",
      "research_revision",
      "contract_version",
      "last_cursor"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "LITERATURE_GRAPH": {
    "domain_fields": [
      "literature_graph_id",
      "node_count",
      "edge_count",
      "source_kinds",
      "graph_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "literature_graph_id",
      "node_count",
      "edge_count",
      "source_kinds",
      "graph_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "DEPLOYMENT",
      "RUN"
    ]
  },
  "LITERATURE_QUERY": {
    "domain_fields": [
      "literature_query_id",
      "source_mode",
      "snapshot_id",
      "query_digest",
      "coverage_boundary"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "literature_query_id",
      "source_mode",
      "snapshot_id",
      "query_digest",
      "coverage_boundary"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT",
      "RUN"
    ]
  },
  "LITERATURE_SOURCE": {
    "domain_fields": [
      "literature_source_id",
      "stable_source_id",
      "source_version",
      "source_kind",
      "content_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "literature_source_id",
      "stable_source_id",
      "source_version",
      "source_kind",
      "content_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT",
      "RUN"
    ]
  },
  "MATERIAL": {
    "domain_fields": [
      "material_id",
      "original_artifact_id",
      "media_type",
      "ingest_state",
      "ocr_state"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "material_id",
      "original_artifact_id",
      "media_type",
      "ingest_state",
      "ocr_state"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "MATERIAL_EXTRACTION": {
    "domain_fields": [
      "extraction_id",
      "material_id",
      "extractor_profile_id",
      "output_artifact_id",
      "extraction_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "extraction_id",
      "material_id",
      "extractor_profile_id",
      "output_artifact_id",
      "extraction_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "NOVELTY_REVIEW": {
    "domain_fields": [
      "novelty_review_id",
      "claim_id",
      "verdict",
      "coverage_snapshot_ids",
      "review_artifact_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "novelty_review_id",
      "claim_id",
      "verdict",
      "coverage_snapshot_ids",
      "review_artifact_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "PRIOR_ART_COMPARISON": {
    "domain_fields": [
      "comparison_id",
      "claim_id",
      "literature_source_id",
      "relationship",
      "comparison_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "comparison_id",
      "claim_id",
      "literature_source_id",
      "relationship",
      "comparison_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "PROBLEM_CANDIDATE": {
    "domain_fields": [
      "problem_candidate_id",
      "problem_pool_id",
      "statement_digest",
      "candidate_state",
      "source_anchor_ids"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "problem_candidate_id",
      "problem_pool_id",
      "statement_digest",
      "candidate_state",
      "source_anchor_ids"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "PROBLEM_POOL": {
    "domain_fields": [
      "problem_pool_id",
      "pool_revision",
      "candidate_count",
      "source_snapshot_ids",
      "selection_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "problem_pool_id",
      "pool_revision",
      "candidate_count",
      "source_snapshot_ids",
      "selection_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "PRODUCT_RECEIPT": {
    "domain_fields": [
      "receipt_id",
      "receipt_state",
      "request_id",
      "receipt_version",
      "revision_after"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "receipt_id",
      "receipt_state",
      "request_id",
      "receipt_version",
      "revision_after"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT",
      "GLOBAL",
      "RUN"
    ]
  },
  "PUBLICATION_STATUS": {
    "domain_fields": [
      "publication_id",
      "finalized_revision",
      "final_outcome",
      "review_state",
      "final_pdf_artifact_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "publication_id",
      "finalized_revision",
      "final_outcome",
      "review_state",
      "final_pdf_artifact_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "RESEARCH_CASE_LINEAGE": {
    "domain_fields": [
      "lineage_id",
      "lineage_mode",
      "source_version",
      "lineage_state",
      "lineage_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "lineage_id",
      "lineage_mode",
      "source_version",
      "lineage_state",
      "lineage_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "RESEARCH_OVERVIEW": {
    "domain_fields": [
      "run_id",
      "outcome_state",
      "execution_state",
      "authority_state",
      "publication_state"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "run_id",
      "outcome_state",
      "execution_state",
      "authority_state",
      "publication_state"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "REVERSE_CLOSURE": {
    "domain_fields": [
      "claim_id",
      "graph_mode",
      "dependable",
      "distance",
      "boundary_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "claim_id",
      "graph_mode",
      "dependable",
      "distance",
      "boundary_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "REVIEW_INBOX": {
    "domain_fields": [
      "review_task_id",
      "review_type",
      "review_state",
      "target_id",
      "target_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "review_task_id",
      "review_type",
      "review_state",
      "target_id",
      "target_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "REVIEW_TASK": {
    "domain_fields": [
      "review_task_id",
      "review_type",
      "review_state",
      "target_id",
      "signed_review_artifact_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "review_task_id",
      "review_type",
      "review_state",
      "target_id",
      "signed_review_artifact_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "REVOKE_PREVIEW": {
    "domain_fields": [
      "revoke_preview_id",
      "target_claim_id",
      "target_digest",
      "closure_digest",
      "affected_claim_ids"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "revoke_preview_id",
      "target_claim_id",
      "target_digest",
      "closure_digest",
      "affected_claim_ids"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "ROUTE_PLAN": {
    "domain_fields": [
      "route_plan_id",
      "plan_revision",
      "plan_state",
      "route_ids",
      "contract_version"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "route_plan_id",
      "plan_revision",
      "plan_state",
      "route_ids",
      "contract_version"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "SOURCE_SNAPSHOT": {
    "domain_fields": [
      "snapshot_id",
      "source_mode",
      "corpus_digest",
      "retrieved_at",
      "coverage_boundary"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "snapshot_id",
      "source_mode",
      "corpus_digest",
      "retrieved_at",
      "coverage_boundary"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "DEPLOYMENT",
      "RUN"
    ]
  },
  "SOURCE_VERSION_HISTORY": {
    "domain_fields": [
      "stable_source_id",
      "source_version",
      "content_digest",
      "supersedes_version",
      "snapshot_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "stable_source_id",
      "source_version",
      "content_digest",
      "supersedes_version",
      "snapshot_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "THEOREM_APPLICABILITY": {
    "domain_fields": [
      "applicability_review_id",
      "theorem_id",
      "claim_id",
      "verdict",
      "review_artifact_id"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "applicability_review_id",
      "theorem_id",
      "claim_id",
      "verdict",
      "review_artifact_id"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "evidence_class",
      "authority_effect",
      "source_artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "TOOL_CATALOG": {
    "domain_fields": [
      "tool_profile_id",
      "profile_version",
      "tool_state",
      "capabilities",
      "authority_ceiling"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "tool_profile_id",
      "profile_version",
      "tool_state",
      "capabilities",
      "authority_ceiling"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "TOOL_RUN": {
    "domain_fields": [
      "tool_run_id",
      "tool_profile_id",
      "run_state",
      "execution_receipt_id",
      "output_artifact_ids"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "tool_run_id",
      "tool_profile_id",
      "run_state",
      "execution_receipt_id",
      "output_artifact_ids"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "USAGE": {
    "domain_fields": [
      "usage_bucket_id",
      "period_start",
      "period_end",
      "resource_type",
      "quantity_microunits"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "usage_bucket_id",
      "period_start",
      "period_end",
      "resource_type",
      "quantity_microunits"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "WORKER_RUN": {
    "domain_fields": [
      "worker_run_id",
      "work_item_id",
      "worker_subject_id",
      "run_state",
      "input_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "worker_run_id",
      "work_item_id",
      "worker_subject_id",
      "run_state",
      "input_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  },
  "WORKFLOW": {
    "domain_fields": [
      "workflow_id",
      "phase",
      "workflow_state",
      "active_work_item_ids",
      "workflow_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "workflow_id",
      "phase",
      "workflow_state",
      "active_work_item_ids",
      "workflow_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "entity",
    "scope_kinds": [
      "RUN"
    ]
  },
  "WORK_ITEM": {
    "domain_fields": [
      "work_item_id",
      "work_kind",
      "work_state",
      "route_id",
      "input_digest"
    ],
    "projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "required_domain_fields": [
      "work_item_id",
      "work_kind",
      "work_state",
      "route_id",
      "input_digest"
    ],
    "required_projection_fields": [
      "schema_version",
      "stable_entity_id",
      "projection_type",
      "status",
      "artifact_ids",
      "domain"
    ],
    "result_kind": "list",
    "scope_kinds": [
      "RUN"
    ]
  }
} as const;

export const COMMAND_CONTRACTS = {
  "AMEND_CONTRACT": {
    "authority_boundary": "KERNEL_GUARDED_INVALIDATION",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "amendment_artifact",
      "base_contract_version",
      "impact_acknowledgement"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "APPLY_ROUTE_PLAN": {
    "authority_boundary": "ORCHESTRATION_ONLY",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [
      "budget",
      "plan_digest",
      "priority",
      "reason"
    ],
    "required_payload_fields": [
      "action",
      "route_plan_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "ASSIGN_ABLATION": {
    "authority_boundary": "RESEARCH_HYPOTHESIS_ONLY",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "ablation_plan_id",
      "budget",
      "candidate_count",
      "final_verifier_profile",
      "group",
      "model_profile",
      "problem_candidate_ids",
      "tool_profile"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "BATCH_CREATE_RESEARCH": {
    "authority_boundary": "KERNEL_GUARDED_CREATE",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "contract_template_artifact",
      "labels",
      "per_run_budget",
      "problem_candidate_ids",
      "problem_pool_id"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "CANCEL_JOB": {
    "authority_boundary": "EXECUTION_STATE_ONLY",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "job_id",
      "reason"
    ],
    "scope_kinds": [
      "RUN",
      "DEPLOYMENT"
    ]
  },
  "CANCEL_RESEARCH": {
    "authority_boundary": "ORCHESTRATION_ONLY",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "cancel_pending_external_attempts",
      "reason"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CLAIM_REVIEW_TASK": {
    "authority_boundary": "NO_FACT_GRAPH_WRITE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "review_task_id",
      "task_binding_digest"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "COMPILE_FINAL_PDF": {
    "authority_boundary": "CLOSED_RUN_PUBLICATION_ONLY",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "candidate_tex_artifact",
      "compiler_profile_id",
      "compiler_profile_version",
      "paper_review_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CONFIRM_CONTRACT": {
    "authority_boundary": "KERNEL_GUARDED_MATH_STATE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "confirmation_note",
      "contract_digest",
      "material_anchor_ids"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CONFIRM_MATERIAL_EXTRACTION": {
    "authority_boundary": "NO_FACT_GRAPH_WRITE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "corrections_artifact",
      "extraction_digest",
      "material_extraction_id",
      "reviewed_page_numbers",
      "source_artifact"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CONFIRM_REVOKE": {
    "authority_boundary": "KERNEL_GUARDED_INVALIDATION",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "affected_fact_ids",
      "contract_version",
      "fact_id",
      "preserved_sibling_ids",
      "preview_revision",
      "reason_artifact",
      "reopened_obligation_ids",
      "target_fact_digest"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CREATE_COMPUTE_TASK": {
    "authority_boundary": "SOFT_TOOL_RESULT_ONLY",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "environment_profile_id",
      "environment_profile_version",
      "expected_output_names",
      "input_artifacts",
      "limits_artifact",
      "parameters_artifact",
      "script_artifact"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "CREATE_RESEARCH": {
    "authority_boundary": "KERNEL_GUARDED_CREATE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [
      "material_artifacts",
      "title"
    ],
    "required_payload_fields": [
      "contract_draft",
      "initial_budget",
      "labels",
      "owner",
      "question"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "CREATE_REVIEW_TASK": {
    "authority_boundary": "NO_FACT_GRAPH_WRITE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "assignee_subject_id",
      "author_subject_ids",
      "expires_at",
      "independence_constraints",
      "review_type",
      "target_digest",
      "target_entity_ids"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "DEPLOYMENT_OPERATION": {
    "authority_boundary": "DEPLOYMENT_STATE_ONLY",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [
      "backup_artifact",
      "backup_id",
      "backup_target",
      "capability_profile_id",
      "component_manifest",
      "configuration_artifact",
      "daemon_id",
      "data_root",
      "drain_timeout_seconds",
      "expected_config_digest",
      "include_cas",
      "include_configuration",
      "inventory_profile_id",
      "new_data_root",
      "redact_credentials",
      "release_manifest"
    ],
    "required_payload_fields": [
      "action"
    ],
    "scope_kinds": [
      "DEPLOYMENT"
    ]
  },
  "FINALIZE_RESEARCH": {
    "authority_boundary": "KERNEL_FINALIZATION_GATE_REQUIRED",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "closure_witness_id",
      "final_outcome",
      "terminal_root_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "FREEZE_PROBLEM_POOL": {
    "authority_boundary": "NO_MATH_OR_NOVELTY_WRITE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "candidate_denominator",
      "exclusion_rules",
      "frozen_at",
      "inclusion_rules",
      "pool_name",
      "semantic_audit_artifact",
      "source_snapshot_ids",
      "subject_classes",
      "version_rule"
    ],
    "scope_kinds": [
      "GLOBAL"
    ]
  },
  "GENERATE_CANDIDATE_TEX": {
    "authority_boundary": "CLOSED_RUN_PUBLICATION_ONLY",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "dependency_closure_digest",
      "finalized_revision",
      "template_artifact",
      "terminal_root_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "IMPORT_RESEARCH_LINEAGE": {
    "authority_boundary": "CANDIDATE_ONLY_NO_FACT_GRAPH_WRITE",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [
      "candidate_artifacts",
      "certificate_import_report",
      "clean_room_input_manifest",
      "historical_conclusions_injected",
      "imported_artifacts",
      "promote_as_verified",
      "verifier_receipt_ids"
    ],
    "required_payload_fields": [
      "mode",
      "source_project_id",
      "source_versions"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "IMPORT_VERIFICATION": {
    "authority_boundary": "KERNEL_VALIDATION_GATE_REQUIRED",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "review_task_id",
      "signed_review_artifact",
      "target_digest",
      "verifier_receipt_ids"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "PAUSE_RESEARCH": {
    "authority_boundary": "ORCHESTRATION_ONLY",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "checkpoint_required",
      "reason"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "REGISTER_BRIDGE_OPPORTUNITY": {
    "authority_boundary": "NO_FACT_GRAPH_WRITE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "candidate_target_domain",
      "domain_distance_basis",
      "expected_certificate_compression",
      "fastest_death_test",
      "mapping_and_assumption_losses",
      "native_tool_advantage",
      "normalized_source_problem",
      "round_trip_and_source_review_cost",
      "selection_rationale",
      "source_method_maturity",
      "source_snapshot_ids",
      "target_domain_absence_evidence"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "REGISTER_BRIDGE_SPEC": {
    "authority_boundary": "KERNEL_VALIDATION_GATE_REQUIRED",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "assumption_loss_artifact",
      "bridge_opportunity_id",
      "composition_obligation_ids",
      "direction",
      "mapping_artifact",
      "source_domain",
      "target_domain",
      "target_review_artifact",
      "translation_artifact"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "REPLAY_SOURCE_SNAPSHOT": {
    "authority_boundary": "NO_MATH_OR_NOVELTY_WRITE",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "expected_response_sha256",
      "reconfirm_external_index",
      "source_snapshot_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "RESUME_RESEARCH": {
    "authority_boundary": "ORCHESTRATION_ONLY",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "checkpoint_id",
      "resume_invalidated_items"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "RETRY_UNKNOWN_OUTCOME": {
    "authority_boundary": "NO_IMPLICIT_MATH_DECISION",
    "execution_class": "EXTERNAL_SIDE_EFFECT",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "evidence_artifact_ids",
      "outcome_unknown_receipt_id",
      "resolution_strategy",
      "unknown_external_call_ref"
    ],
    "scope_kinds": [
      "RUN",
      "DEPLOYMENT"
    ]
  },
  "REVIEW_THEOREM_APPLICABILITY": {
    "authority_boundary": "NO_FACT_GRAPH_WRITE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "assumption_mapping_artifact",
      "signed_review_artifact",
      "target_claim_id",
      "theorem_source_binding",
      "verdict"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "RUN_LITERATURE_QUERY": {
    "authority_boundary": "NO_MATH_OR_NOVELTY_WRITE",
    "execution_class": "EXTERNAL_SIDE_EFFECT",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "capture_raw_response",
      "connector_profile_ids",
      "coverage_boundary",
      "query_text",
      "research_question",
      "target_entity_ids"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "RUN_TOOL": {
    "authority_boundary": "TOOL_RECEIPT_NOT_AUTHORITY",
    "execution_class": "EXTERNAL_SIDE_EFFECT",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "arguments_artifact",
      "authority_ceiling",
      "function_name",
      "function_schema_digest",
      "input_artifact_ids",
      "tool_id",
      "tool_version"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "START_RESEARCH": {
    "authority_boundary": "ORCHESTRATION_ONLY",
    "execution_class": "DURABLE_JOB",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "checkpoint_id",
      "route_plan_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "SUBMIT_CLAIM": {
    "authority_boundary": "KERNEL_VALIDATION_GATE_REQUIRED",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [
      "public_summary",
      "route_id",
      "supersedes_claim_id"
    ],
    "required_payload_fields": [
      "attempt_id",
      "claim_kind",
      "predecessor_fact_ids",
      "proof_or_evidence_artifacts",
      "source_binding_artifact",
      "statement",
      "work_item_id",
      "worker_run_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "SUBMIT_CLOSURE_WITNESS": {
    "authority_boundary": "KERNEL_CLOSURE_GATE_REQUIRED",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "bridge_spec_ids",
      "composition_obligation_ids",
      "edge_justification_artifacts",
      "graph_revision",
      "selected_subgraph_digest",
      "terminal_root_id",
      "verification_review_ids"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "SUBMIT_GUIDANCE": {
    "authority_boundary": "NO_FACT_GRAPH_WRITE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "affected_route_ids",
      "goal",
      "guidance_text",
      "target_checkpoint_id"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "SUBMIT_PAPER_REVIEW": {
    "authority_boundary": "SIGNED_PAPER_REVIEW_ONLY",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "candidate_tex_artifact",
      "paper_review_schema_version",
      "review_task_id",
      "signed_paper_review_artifact"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "SUBMIT_REVIEW": {
    "authority_boundary": "SIGNED_REVIEW_ONLY",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "review_schema_version",
      "review_task_id",
      "signed_review_artifact",
      "task_binding_digest"
    ],
    "scope_kinds": [
      "RUN"
    ]
  },
  "WITHDRAW_GUIDANCE": {
    "authority_boundary": "NO_FACT_GRAPH_WRITE",
    "execution_class": "IMMEDIATE",
    "optional_payload_fields": [],
    "required_payload_fields": [
      "guidance_id",
      "reason"
    ],
    "scope_kinds": [
      "RUN"
    ]
  }
} as const;
