"""Generate dependency-free SDK surfaces from the frozen product contracts."""
# ruff: noqa: E501

from __future__ import annotations

import json
import pprint
from pathlib import Path

from rkb01bqueryshape import generate as generate_b01b_query_shape
from rkcommandcontract import generate as generate_command_contract
from rkcommandcontract import metadata as command_metadata
from rkquerycontract import generate as generate_query_contract
from rkquerycontract import metadata as query_metadata

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "docs" / "spec" / "product" / "catalog.json"


def _python_enum(name: str, values: list[str]) -> str:
    members = "\n".join(f'    {value} = "{value}"' for value in values)
    return f"class {name}(StrEnum):\n{members}\n"


def _typescript_union(name: str, values: list[str]) -> str:
    body = " | ".join(json.dumps(value) for value in values)
    return f"export type {name} = {body};\n"


def main() -> None:
    generate_command_contract(ROOT)
    generate_b01b_query_shape(ROOT)
    generate_query_contract(ROOT)
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    py = [
        '"""Generated by scripts/rkgenerateproduct.py; do not edit."""',
        "",
        "from enum import StrEnum",
        "from typing import Final, TypedDict",
        "",
        "",
    ]
    ts = [
        "// Generated by scripts/rkgenerateproduct.py; do not edit.",
        "",
        "export type CommandFieldValue = null | boolean | number | string | CommandFieldValue[] | {readonly [key: string]: CommandFieldValue};",
        "",
    ]
    mapping = {
        "ScopeKind": "scope_kinds",
        "ReceiptState": "receipt_states",
        "CommandType": "command_types",
        "QueryType": "query_types",
        "ArtifactOperationType": "artifact_operations",
        "ReviewType": "review_types",
        "WorkflowObjectType": "workflow_object_types",
        "PublicActivitySource": "public_activity_sources",
        "ProductErrorCode": "error_codes",
    }
    for type_name, key in mapping.items():
        py.append(_python_enum(type_name, catalog[key]))
        ts.append(_typescript_union(type_name, catalog[key]))
    contract = command_metadata()
    py += [
        "class CommandContract(TypedDict):",
        "    scope_kinds: list[str]",
        "    execution_class: str",
        "    authority_boundary: str",
        "    required_payload_fields: list[str]",
        "    optional_payload_fields: list[str]",
        "",
        "COMMAND_CONTRACTS: Final[dict[str, CommandContract]] = (\n"
        + pprint.pformat(contract, width=88, sort_dicts=True)
        + "\n)\n",
    ]
    ts.append("export interface CommandPayloadMap {")
    for command_type, spec in contract.items():
        members = [f"{field}: CommandFieldValue" for field in spec["required_payload_fields"]]
        members += [f"{field}?: CommandFieldValue" for field in spec["optional_payload_fields"]]
        ts.append(f"  {command_type}: {{{'; '.join(members)}}};")
    ts += [
        "}",
        "",
        "export type ProductCommand = {[K in CommandType]: {type: K; payload: CommandPayloadMap[K]}}[CommandType];",
        "",
    ]
    queries = query_metadata(ROOT)
    py += [
        "class QueryContract(TypedDict):",
        "    scope_kinds: list[str]",
        "    required_payload_fields: list[str]",
        "    optional_payload_fields: list[str]",
        "",
        "QUERY_CONTRACTS: Final[dict[str, QueryContract]] = (\n"
        + pprint.pformat(queries, width=88, sort_dicts=True)
        + "\n)\n",
    ]
    ts.append("export interface QueryPayloadMap {")
    for query_type, spec in queries.items():
        members = [f"{field}: CommandFieldValue" for field in spec["required_payload_fields"]]
        members += [f"{field}?: CommandFieldValue" for field in spec["optional_payload_fields"]]
        ts.append(f"  {query_type}: {{{'; '.join(members)}}};")
    ts += ["}", ""]
    ts.append(
        "export const QUERY_CONTRACTS = "
        + json.dumps(queries, ensure_ascii=False, indent=2, sort_keys=True)
        + " as const;"
    )
    ts.append("")
    ts.append(
        "export const COMMAND_CONTRACTS = "
        + json.dumps(contract, ensure_ascii=False, indent=2, sort_keys=True)
        + " as const;"
    )
    ts.append("")
    py_target = ROOT / "sdk" / "python" / "rk_product" / "types.py"
    ts_target = ROOT / "sdk" / "typescript" / "src" / "types.ts"
    py_target.parent.mkdir(parents=True, exist_ok=True)
    ts_target.parent.mkdir(parents=True, exist_ok=True)
    py_target.write_text("\n".join(py), encoding="utf-8", newline="\n")
    ts_target.write_text("\n".join(ts), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
