"""Generate dependency-free SDK enum surfaces from the frozen product catalog."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "docs" / "spec" / "product" / "catalog.json"


def _python_enum(name: str, values: list[str]) -> str:
    members = "\n".join(f'    {value} = "{value}"' for value in values)
    return f"class {name}(StrEnum):\n{members}\n"


def _typescript_union(name: str, values: list[str]) -> str:
    body = " | ".join(json.dumps(value) for value in values)
    return f"export type {name} = {body};\n"


def main() -> None:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    py = [
        '"""Generated by scripts/rkgenerateproduct.py; do not edit."""',
        "",
        "from enum import StrEnum",
        "",
        "",
    ]
    ts = ["// Generated by scripts/rkgenerateproduct.py; do not edit.", ""]
    mapping = {
        "ScopeKind": "scope_kinds",
        "ReceiptState": "receipt_states",
        "CommandType": "command_types",
        "QueryType": "query_types",
        "ArtifactOperationType": "artifact_operations",
        "ReviewType": "review_types",
        "WorkflowObjectType": "workflow_object_types",
        "PublicActivitySource": "public_activity_sources",
        "ProductErrorCode": "error_codes",
    }
    for type_name, key in mapping.items():
        py.append(_python_enum(type_name, catalog[key]))
        ts.append(_typescript_union(type_name, catalog[key]))
    py_target = ROOT / "sdk" / "python" / "rk_product" / "types.py"
    ts_target = ROOT / "sdk" / "typescript" / "src" / "types.ts"
    py_target.parent.mkdir(parents=True, exist_ok=True)
    ts_target.parent.mkdir(parents=True, exist_ok=True)
    py_target.write_text("\n".join(py), encoding="utf-8", newline="\n")
    ts_target.write_text("\n".join(ts), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
